### ISSUE TITLE
Global view

### ISSUE THREAD

**Issue by liomoura** [alexbevi/redmine_knowledgebase#280]
why the global view has been removed from the line 3.x?

**Comment by alexbevi** [comment]
@liomoura, the general consensus among users was that they wanted (1) project-specific knowledgebase instances, and (2) the ability to search for articles using the Redmine search functions.

The global approach of the 1.0 knowledgebase required a lot of 'hackery' in order to allow searching.

Users also wanted to be able to limit visibility of articles, which could be accomplished using Redmine's permission system (as it is project-specific).

If you still want to have the global knowledgebase, the easiest way to do this is:

* create a public project
* add the knowledgebase to this project
* install the [menu_link](https://github.com/Tide/menu_link) plugin
* create a link to the public project's knowledgebase

**Comment by liomoura** [comment]
Thank you so much!
