### ISSUE TITLE
Compatibility with Redmine 3.3.0

### ISSUE THREAD

**Issue by ehvidal** [alexbevi/redmine_knowledgebase#332]
Thank you very much for your fine job! I have been using your plugin for the last 5 years and I think it's awesome.

Now I'm planning to migrate my Redmine to 3.3.0, so my question is, are you planning to make your plugin compatible with Redmine 3.3.0 soon? Do you have some idea about when it will be published?

Again, thank you very much for your excellent work!

**Comment by alexbevi** [comment]
@ehvidal I'm just pushing out 3.2.1 which fixes the search issue in 3.2 of Redmine. I haven't tested with Redmine 3.3.0 yet, but i'm assuming they should be compatible.

**Comment by NicoKlein** [comment]
Today i try it on 3.3.0 but get: 
Retrying git clone 'git://github.com/alexbevi/redmine_acts_as_taggable_on.git' "/usr/local/rvm/gems/ruby-2.1.9/cache/bundler/git/redmine_acts_as_taggable_on-82f0b3fd11b92d791c4838695491decb70c3b979" --bare --no-hardlinks --quiet due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/alexbevi/redmine_acts_as_taggable_on.git' "/usr/local/rvm/gems/ruby-2.1.9/cache/bundler/git/redmine_acts_as_taggable_on-82f0b3fd11b92d791c4838695491decb70c3b979" --bare --no-hardlinks --quiet` in directory /opt/redmine/redmine-3.3.0 has failed.
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection timed out

**Comment by okolimar** [comment]
Hi @alexbevi ,

thanks for the great work! Unfortunately it is not working for me in 3.3 either.

**Comment by moppi83** [comment]
Hello,

i also installed plugin_knowledgebase on redmine 3.3.0. It works but only for admin-user.
If I log in as normal user i can select the plugin for my project but there is no link in the menu bar of redmine. Is there a solution?

Best regards

**Comment by DarkSideGeek** [comment]
Possibly because you need to enable some module-specific permissions in your various roles?

**Comment by moppi83** [comment]
Hi DarkSideGeek,

you are right; Sorry for the simply question. I'm new to redmine and a did not recognized the roles-site.

I can confirm that the plugin works with redmine 3.3.0

**Comment by alexbevi** [comment]
I don't think 3.3.x compatibility is still an issue
