### ISSUE TITLE
Compatibility with Redmine CRM Plugins

### ISSUE THREAD

**Issue by 6tem9** [alexbevi/redmine_knowledgebase#333]
Hi,
Once the plugin enabled Knowledge Base, tags no longer work, on projects or on the users , and on Articles Knowledge Base .
If we add one tag , we are faced with a server error.
Is there a solution ?
Thanks in advance.

**Comment by bluenevus** [comment]
same here

**Comment by djfml** [comment]
I met the same fault.
how could I use the knowledge plugins  the same time  if
I don't wants to uninstall CRM plugins such as redmine _contacts?

**Comment by alexbevi** [comment]
@6tem9 @bluenevus @djfml this has been an ongoing issue for a number of years across a number of plugins. The issue has to do with all plugins trying to maintain their own tagging functionality, but since they all rely on the same tables, there are generally conflicts with installation or usage.

I don't have a good solution yet, but this is definitely high on the priority list (and has been for a while now)

**Comment by mathiaswallgren** [comment]
I also have this problem and I am not very good with Ruby. I already had the CRM plugin (which I am not using) and redmine_knowledgebase would not work. I tried to uninstall the CRM plugin which failed and I tried to uninstall this plugin which also failed. Now my the nginx server will not start and my Redmine site is down and I have tried to find a solution and spent several hours on this because I have a lot of data in Redmine and use it every day. The error I get when I try an uninstall is that the source for redmine_acts_as_taggable is not yet checked out. If I try a bundle install I get a message saying that the version for this gem in the gemfile is ~>4.0 and redmine_acts_as_taggable was resolved to 1.1.0, which depends ~>3.4. Any suggestions how I can resolve this? I'd really would like this plugin, but now I just need to get Redmine working again.
![error](https://cloud.githubusercontent.com/assets/15824187/24612953/209c44d8-18ca-11e7-88e3-da5720051f8b.JPG)

**Comment by pousterlus** [comment]
Hey,

Just checking if the Redmine 3.4 release helped to move forward on this ?
Or is it the same situation now ?

Your knowledge base is the best I could find out there for Redmine, but I unfortunately can't install it with Redmine Helpdesk from RedmineCRM :)

Thanks,

-- 
Léo.

**Comment by pousterlus** [comment]
Hello there,

Still no clue about how to fix this ?
Your plugin is perfect for us, but we must use Helpdesk plugin, which uses another tagging system.
And as Helpdesk was installed before Knowledge base, I can't put Helpdesk aside...

Many thank,

-- 
Léo.

**Comment by alexbevi** [comment]
@pousterlus the only "fix" at this point would be for every plugin to user their own namespaced tags implementation (which would suck), or a common tags gem (like the redmine_acts_as_taggable_on gem).

Since there is no standard and all authors do "their own thing", this is not an easy problem to address.

The best case scenario would be to have tagging integrated into Redmine core, and have it accessible to all plugins. Then they would all _have_ to rewrite to use the common library (which there is no incentive to do at this point).
